### ISSUE TITLE
# Save file BUG.

### ISSUE THREAD

**Issue by DNature** [Hardocs/desktop-app#42]
## Current behavior
- When a person clicks on save for the first time the file will be created successfully.
- But when you update your content and tries to re-save your changes, the file will be deleted because instead of being updated or re-created.

## Expected behavior
- When a person clicks on save for the first time a file is supposed to be created.
- After updating the content and you want to save the content into the created file the previous version is supposed to be truncated then a new file will be created.

## Platforms
- Currently tested on Linux (Ubuntu)

**Comment by jurra** [comment]
Thanks for reporting the bug @DNature there is something going on with the state.
Will work that out tomorrow 😅 !

**Comment by jurra** [comment]
I just solved this one ;)

**Comment by DNature** [comment]
Wow. That was quick.

**Comment by DNature** [comment]
Wow. That was quick.
