### ISSUE TITLE
Fs package readme, license, and versioning...

### ISSUE THREAD

**Issue by jurra** [Hardocs/desktop-app#50]

**Comment by jurra** [comment]
@DNature We are still having a readme in hardocs-fs metiniong graphql, lacking a license and an explanation.
Can you take care of this?

You can use this simple template to do that: [README-Template.md](https://gist.github.com/DomPizzie/7a5ff55ffa9081f2de27c315f5018afc)
For licensing use Apache https://www.apache.org/licenses/LICENSE-2.0

**Comment by DNature** [comment]
I have added The license file, Readme and contributors badge for hardocs-fs. Check it out here <https://github.com/Hardocs/hardocs-fs/tree/feature/readme#hardocs-fs-file-system-module>. I'd like feedback on this PR

**Comment by jurra** [comment]
I just checked, I am closing this one also :)
