### ISSUE TITLE
release isn't ready to be used yet by developers

### ISSUE THREAD

**Issue by narration-sd** [Hardocs/desktop-app#57]
The release/v0.1.2 branch is improperly requiring a GitHub token to build it, after normal pull. This is apparently from some operations  in CI/CD, but a token requirement must not appear on the release branch, so this needs to be fixed.

As well, the branch is actually building a result called Hardocs Desktop-0.1.1-beta-win.zip . This needs to be corrected to match the release -- as 0.1.2, but please, as alpha.  It is not a beta in any way.

There are minimal Guide documents at this point, but that is probably due to the limited first functionality.

The master branch seems to be unbuildable even as electron:serve on Windows -- please assure development activities are always on feature/branches, so that develop and master are always buildable. This is very important...

**Comment by jurra** [comment]
@narration-sd I guess you mean mostly by developers. Are you also refering to the downloadable items?
Those should be fine. It would be great if also @santoshilam could give some feedback.

**Comment by DNature** [comment]
Yeah. I have also noticed that it's no longer necessary to include the `github_token` since we're no longer publishing to snapcraft.

see [https://github.com/samuelmeuli/action-electron-builder#setup](https://github.com/samuelmeuli/action-electron-builder#setup)

**Comment by narration-sd** [comment]
on downloadables, which I can't yet find, am presuming the naming is also incorrect -- really needs not to ever be 'beta', in this contract.  Must be alpha; please assure.

**Comment by narration-sd** [comment]
One more thing is that there needs to be be a line early in the Readme, saying that there are downloads, and giving a link to them directly (their location under Releases). 

This is common practice.

**Comment by narration-sd** [comment]
...just not a false alarm, about naming in building by developers. Please make that correct...alpha...and current version number, thanks.

**Comment by narration-sd** [comment]
One more:  I am using the release branch to attempt merging of current metadata editor work, and still receiving the following.

Couldn't find any versions for "hardocs-ck-editor" that matches "git@github.com:Hardocs/editor.git"
? Please choose a version of "hardocs-ck-editor" from this list: (Use arrow keys)
> 0.0.3-beta
  0.0.2-beta
  0.0.1-beta

Please repair so this doesn't happen. I'm taking the first choice, in hope it will work for now...

**Comment by jurra** [comment]
@DNature did you address this issue already? Are you able to take over this?
If you already solved this issue let me know to close it.

**Comment by DNature** [comment]
@jurra I have published the current version and most recent changes of `hardocs-ck-editor` to npm [https://www.npmjs.com/package/hardocs-ck-editor?activeTab=versions](https://www.npmjs.com/package/hardocs-ck-editor?activeTab=versions) about a month ago and it no longer prompts you to select a version during `yarn install`. I will push the changes to github now to resolve this issue.

**Comment by DNature** [comment]
I now have it up on `release/v0.1.2` branch. Here's a pull request i made [https://github.com/Hardocs/desktop-app/pull/63](https://github.com/Hardocs/desktop-app/pull/63)

**Comment by jurra** [comment]
Thanks @DNature , I am checking this, it should be actually a hotfix directly branched from master.
If we are going to change even a bit the master branch we have to properly patch it v0.1.3.

**Comment by jurra** [comment]
I am reviewing your PR now 😃

**Comment by jurra** [comment]
I think we are ready to close this one
