### ISSUE TITLE
CK-Editor will be invisible when  installing hardocs without an internet connection

### ISSUE THREAD

**Issue by jurra** [Hardocs/desktop-app#59]
## Current behavior
When the app is executed offline the ckeditor will not show in the app, instead it will show this:

![image](https://user-images.githubusercontent.com/18581201/104787854-0030ba80-5791-11eb-9200-6ede3335baa1.png)

As it can be seen the editor doesnt show properly

## Desired behavior
When the app is opened offline it should look like the picture below.
![image](https://user-images.githubusercontent.com/18581201/104787930-3d954800-5791-11eb-93ed-376e6378f96f.png)

The editor should work offline as well as it works now when connected.

**Comment by jurra** [comment]
This is happening because of a call being made by the MathType module,

Hey 🥇 @DNature it would be great if you could rebuild the editor without this particular module, 
I am currently working on `hotfix/npm-ckeditor-module` you can update the packagejson and let me know when that is ready, I can then integrate it back again and review it.

Thanks in advance 😄

**Comment by DNature** [comment]
Okay. I will do that first thing tomorrow

**Comment by DNature** [comment]
- [ x ] publish new hardocs-ck-editor to npm
- [ ] Install the latest version of `hardocs-editor` in the desktop app
- [ ] Test out the workflow build
- [ ] draft a new release
- [ ] publish the new release

**Comment by jurra** [comment]
This is solved, at implited sacrifycing the Math module. We need to keep an eye on that module development, because this is a pending issue I saw on their repository.
