### ISSUE TITLE
How to test the vuex store with electron and jest

### ISSUE THREAD

**Issue by DNature** [Hardocs/desktop-app#68]
#### I was in the process of writing the first test for `hardocs-desktop-app` and this must include `Vuex store`; However, I'm getting this error and it's pointing to `habitat-client`:

```bash
Test suite failed to run

    TypeError: Cannot read property 'dialog' of undefined

      at Object.<anonymous> (node_modules/@hardocs-project/habitat-client/lib/modules/habitat-localservices.js:31:31)
      at Object.<anonymous> (node_modules/@hardocs-project/habitat-client/lib/modules/habitat-database.js:10:29)
```

#### Steps to reproduce the issue

1. Clone `feature/testing` branch
2. Install dependencies with `yarn` 
3. run tests: `yarn test`

#### Screenshot

![image](https://user-images.githubusercontent.com/49137104/107352559-46e1ae00-6acc-11eb-977a-1323a162a311.png)

**Comment by DNature** [comment]
@narration-sd Please take a look at this

**Comment by jurra** [comment]
@DNature It seems to me that `dialog` is an electron related module or function.
Therefore I suspect you have to import electron in your test script in order for it to work. Did you try this?
Check this also it can be relevant: [https://www.electronjs.org/docs/api/dialog](https://www.electronjs.org/docs/api/dialog)

**Comment by narration-sd** [comment]
On the surface, looks @jurra is likely on the right traiil with this.  As far as I know dialog works fine - it's in use, and the Electron side is solid.

**Comment by DNature** [comment]
I imported the dialog module from electron but it still did not work, I also tried the remote module but it didn't work.

#### Code example
```js
import { createLocalVue } from '@vue/test-utils';
const { dialog } = require('electron').remote;

import Vuex from 'vuex';
import * as docs from '../docs';

const localVue = createLocalVue();
localVue.use(Vuex);

describe('Test for docs operations', () => {
  const store = new Vuex.Store({
    modules: {
      docs
    }
  });

  console.log(dialog);

  console.log(store.state.actions.cwd);
});
```

**Comment by DNature** [comment]
I also noticed that `habitat client` does not include `electron` as a dependency, therefore, destructuring `dialog` will not work.

![image](https://user-images.githubusercontent.com/49137104/107513523-a0b7a600-6ba8-11eb-9d5f-0926ac48f843.png)

![image](https://user-images.githubusercontent.com/49137104/107513559-af9e5880-6ba8-11eb-80ac-baa5f96edc43.png)

**Comment by DNature** [comment]
I found this hack <https://github.com/electron/electron/issues/3909#issuecomment-568048005>, However, Another issue came up: 

![image](https://user-images.githubusercontent.com/49137104/107533430-38c08a00-6bbf-11eb-9872-f3376280f7ad.png)

**Comment by narration-sd** [comment]
Divine, I think it's more a nature of what is actually running, operating, than of importing libraries.

In fact, you should not, and should not have to be, importing anything but the habitat-client -- it would be at least redundant, and at worst interfere.

Electron is a quite complex multi-thread-process machine, with much internal interaction expected, and it's not going to work for you unless it's all properly initiated and operating.

In this test you are trying to do, is there a fully running Electron user interface showing on a terminal? Probably not. Then you need to do as we do in the software profession, look for what other persons make available for the problem, have themselves done.

I made a simple Google query ('unit testing Electron applications') and immediately found these two links. The first is a useful overview, minus the later part which is selling. The second is the free testing framework that he is talking about, which is built into Electron, Spectron.

    https://smartbear.com/blog/how-to-test-electron-apps/
    https://www.electronjs.org/spectron

At first glance, anyway, Spectron appears to be fully aware and ready to help you for tests that involve with the multi-threads and the ui -- as they should understand the challenge

**Comment by DNature** [comment]
Thank you for the `spectron` package you suggested. I never knew that electron has a different test system.

I will definitely look into it ASAP

**Comment by jurra** [comment]
We made a first progress and learned how to test vuex with jest using mocks without having to depend on electron to do the tests.
But we might need to test also electron features like ipc messaging, and for this particular case we need to use spectron.
