### ISSUE TITLE
Being passed from the state to the vuetify form component 

### ISSUE THREAD

**Issue by jurra** [Hardocs/desktop-app#78]
## Report bug properly

**Comment by DNature** [comment]
After integrating `vjfs` for schema, the supposed behavior of creating a hardocs project in the UI changed.

### Previous (expected) behavior.
- After clicking on the `create project` button, a file system dialog comes up for a user to select a folder to store a new project and hits ok. 
- Hardocs would process the folder path you selected and pass it to the JSON schema to update the form default state.
- The form default state now has a pre-defined path based on the selected folder, and the docs dir and entry path is populated with `docs` and `index.html` as the default state.

### Current behavior:
- The state is not being populated with the specified path and other state properties. -- It's basically empty.

**Comment by DNature** [comment]
After debugging,

I noticed that we do not have to load the schema with a ref because `vjfs` does that automatically.

```diff
created(){
  - this.schema.then((schema) => {
  -     return this.$refs.formSchema.load(schema);
  -   });
  this.model.path = this.cwd;
  this.model.docsDir = 'docs';
  this.model.entryFile = 'index.html';
}
```

**Comment by jurra** [comment]
We need to pass the stae of that specific component into the main state
