### ISSUE TITLE
Implement edit, preview views for each document

### ISSUE THREAD

**Issue by jurra** [Hardocs/desktop-app#81]
# Checklist
- [x] Use standard edit save icon 
- [x] Default is preview
- [x] Save button

## We have two options: 
1. Uses preview button
2. When saved goes to preview automatically

**Comment by DNature** [comment]
![Uploading Viewer 2_ Showing attachments.png…]()

**Comment by DNature** [comment]
![Viewer 2_ Showing attachments](https://user-images.githubusercontent.com/49137104/110754081-ace66000-8247-11eb-905b-c4b02aa12f68.png)
